version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - myrailsapp_bundle:/app/vendor/bundle
      - myrailsapp_node_modules:/app/node_modules

  app-nginx:
    build:
      context: .
      dockerfile: Dockerfile-buildkit
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - nginx
    volumes:
      - .:/app
      - myrailsapp_bundle:/app/vendor/bundle
      - myrailsapp_node_modules:/app/node_modules
      - myrailsapp_public:/app/public
      - myrailsapp_socket:/app/sockets

  nginx:
    image: nginx:1.17
    ports:
      - "8080:80"
    command: [nginx]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - myrailsapp_public:/app/public
      - myrailsapp_socket:/app/sockets


volumes:
  mysql-data:
    driver: local
  myrailsapp_bundle:
    driver: local
  myrailsapp_node_modules:
    driver: local
  myrailsapp_socket:
    driver: local
  myrailsapp_public:
    driver: local
